name: build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4

      - name: setup
        uses: ezisofg/setup-theos@v1
        with:
          sdk-version: '14.5'

      - name: compile
        run: |
          export THEOS=~/theos
          make package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=roothide

      - uses: actions/upload-artifact@v4
        with:
          name: RebellionAlert-DEB
          path: packages/*.deb
