name: Build Rebellion Tweak

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare Theos
        uses: actions/cache@v4
        with:
          path: ~/theos
          key: ${{ runner.os }}-theos

      - name: Setup Theos Action
        uses: ArthurGekko/setup-theos-action@v1.1.1
        with:
          theos-src: https://github.com/theos/theos.git

      - name: Build Package (Roothide)
        run: |
          export THEOS=~/theos
          make package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=roothide

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: RebellionAlert-DEB
          path: packages/*.deb
