name: build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4

      - name: setup
        run: |
          git clone -q --recursive https://github.com/roothide/theos.git ~/theos
          rm -rf ~/theos/sdks
          git clone -q --depth=1 https://github.com/theos/sdks.git ~/theos/sdks
          echo "THEOS=~/theos" >> $GITHUB_ENV

      - name: compile
        run: |
          export THEOS=~/theos
          make package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=roothide

      - uses: actions/upload-artifact@v4
        with:
          name: RebellionAlert-DEB
          path: packages/*.deb
